In [89]:
import numpy as np
import pandas as pd

import os
from scipy.stats import skew
from scipy.stats.stats import pearsonr
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [90]:
file_path = "/Users/alexjzy/Desktop/Py-Projects/NUS-CI1-CA1/dataset/brooklyn_sales_map.csv"

data = pd.read_csv(file_path, low_memory = False)

In [91]:
data.head(3)

,Unnamed: 0,borough,neighborhood,building_class_category,tax_class,block,lot,easement,building_class,address,...,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_FLA,PFIRM15_FL,Version,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,1,3,DOWNTOWN-METROTECH,28 COMMERCIAL CONDOS,4,140,1001,NaN,R5,330 JAY STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,3,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,NaN,G7,85 JAY STREET,...,NaN,3.000540e+09,12/06/2002,1.0,NaN,NaN,17V1.1,0.0,1559.889144,140131.577176
2,3,3,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,NaN,O6,29 COLUMBIA HEIGHTS,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,890.718521,34656.447240

In [92]:
##check data types
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print (data.dtypes)

Unnamed: 0                   int64
borough                      int64
neighborhood                object
building_class_category     object
tax_class                   object
block                        int64
lot                          int64
easement                   float64
building_class              object
address                     object
apartment_number            object
zip_code                     int64
residential_units            int64
commercial_units             int64
total_units                  int64
land_sqft                  float64
gross_sqft                 float64
year_built                   int64
tax_class_at_sale            int64
building_class_at_sale      object
sale_price                 float64
sale_date                   object
year_of_sale                 int64
Borough                     object
CD                         float64
CT2010                     float64
CB2010                     float64
SchoolDist                 float64
Council                    float64
ZipCode                    float64
FireComp                    object
PolicePrct                 float64
HealthCent                 float64
HealthArea                 float64
SanitBoro                  float64
SanitDistr                 float64
SanitSub                    object
Address                     object
ZoneDist1                   object
ZoneDist2                   object
ZoneDist3                   object
ZoneDist4                   object
Overlay1                    object
Overlay2                    object
SPDist1                     object
SPDist2                     object
SPDist3                     object
LtdHeight                   object
SplitZone                   object
BldgClass                   object
LandUse                    float64
Easements                  float64
OwnerType                   object
OwnerName                   object
LotArea                    float64
BldgArea                   float64
ComArea                    float64
ResArea                    float64
OfficeArea                 float64
RetailArea                 float64
GarageArea                 float64
StrgeArea                  float64
FactryArea                 float64
OtherArea                  float64
AreaSource                 float64
NumBldgs                   float64
NumFloors                  float64
UnitsRes                   float64
UnitsTotal                 float64
LotFront                   float64
LotDepth                   float64
BldgFront                  float64
BldgDepth                  float64
Ext                         object
ProxCode                   float64
IrrLotCode                  object
LotType                    float64
BsmtCode                   float64
AssessLand                 float64
AssessTot                  float64
ExemptLand                 float64
ExemptTot                  float64
YearBuilt                  float64
YearAlter1                 float64
YearAlter2                 float64
HistDist                    object
Landmark                    object
BuiltFAR                   float64
ResidFAR                   float64
CommFAR                    float64
FacilFAR                   float64
BoroCode                   float64
BBL                        float64
CondoNo                    float64
Tract2010                  float64
XCoord                     float64
YCoord                     float64
ZoneMap                     object
ZMCode                      object
Sanborn                     object
TaxMap                     float64
EDesigNum                   object
APPBBL                     float64
APPDate                     object
PLUTOMapID                 float64
FIRM07_FLA                 float64
PFIRM15_FL                 float64
Version                     object
MAPPLUTO_F                 float64
SHAPE_Leng                 float64
SHAPE_Area                 float64
dtype: object

In [93]:
##data selection, house saled in 2017
data = data[data.year_of_sale == 2017]
data

,Unnamed: 0,borough,neighborhood,building_class_category,tax_class,block,lot,easement,building_class,address,...,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_FLA,PFIRM15_FL,Version,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
4,5,3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,NaN,H8,21 CLARK STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,620.761169,21360.147631
6,7,3,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,250,44,NaN,O4,16 COURT STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,460.031680,12947.145471
10,11,3,WILLIAMSBURG-NORTH,41 TAX CLASS 4 - OTHER,4,2287,16,NaN,Z9,20 NORTH 12 STREET,...,E-138,0.000000e+00,NaN,1.0,1.0,1.0,17V1.1,0.0,1031.123666,63814.710780
13,14,3,DOWNTOWN-METROTECH,21 OFFICE BUILDINGS,4,63,1,NaN,O6,55 PROSPECT STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,621.710684,21360.030189
15,16,3,DOWNTOWN-METROTECH,26 OTHER HOTELS,4,87,9,NaN,H8,90 SANDS STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,631.446196,21861.418457
19,20,3,DOWNTOWN-METROTECH,21 OFFICE BUILDINGS,4,77,1,NaN,O6,77 SANDS STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,530.358673,16225.644674
26,27,3,DOWNTOWN-METROTECH,21 OFFICE BUILDINGS,4,87,5,NaN,O6,175 PEARL STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,635.147432,22260.162205
28,29,3,DOWNTOWN-METROTECH,21 OFFICE BUILDINGS,4,76,1,NaN,O6,117 ADAMS STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,633.876660,22634.613751
35,36,3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,224,5,NaN,H8,107 COLUMBIA HEIGHTS,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,616.056218,21001.984085
56,57,3,FORT GREENE,22 STORE BUILDINGS,4,2094,35,NaN,K4,633-635 FULTON ST,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,485.003860,13224.881521
69,70,3,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,51,25,NaN,G1,74 ADAMS STREET,...,NaN,3.000510e+09,03/25/2011,1.0,NaN,NaN,17V1.1,0.0,779.571398,24963.517624
77,78,3,BROOKLYN HEIGHTS,08 RENTALS - ELEVATOR APARTMENTS,2,219,1,NaN,D9,97 COLUMBIA HEIGHTS,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,562.935418,7726.428939
81,82,3,WILLIAMSBURG-SOUTH,08 RENTALS - ELEVATOR APARTMENTS,2,2159,1,NaN,D9,475 KENT AVENUE,...,E-91,3.021590e+09,12/29/2013,1.0,NaN,NaN,17V1.1,0.0,684.590540,25471.032019
86,87,3,BROWNSVILLE,33 EDUCATIONAL FACILITIES,4,3492,1,NaN,W9,1501 PITKIN,...,NaN,3.034920e+09,04/14/2008,1.0,NaN,NaN,17V1.1,0.0,730.241329,31159.103918
87,88,3,CANARSIE,30 WAREHOUSES,4,3650,28,NaN,E7,1098 ROCKAWAY AVENUE,...,NaN,3.036500e+09,08/13/2015,1.0,NaN,NaN,17V1.1,0.0,1253.699337,82862.661173
89,90,3,DOWNTOWN-FULTON MALL,29 COMMERCIAL GARAGES,4,157,1,NaN,G1,15 HOYT STREET,...,NaN,3.001570e+09,02/25/1986,1.0,NaN,NaN,17V1.1,0.0,1010.969784,62530.873544
94,95,3,BROOKLYN HEIGHTS,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,239,16,NaN,V1,280 CADMAN PLAZA WEST,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,702.111881,26116.439809
97,98,3,BUSHWICK,08 RENTALS - ELEVATOR APARTMENTS,2,3170,26,NaN,D1,626 BUSHWICK AVENUE,...,NaN,3.031700e+09,09/23/2013,1.0,NaN,NaN,17V1.1,0.0,810.649949,28578.268442
100,101,3,DOWNTOWN-METROTECH,21 OFFICE BUILDINGS,4,64,25,NaN,O6,81 PROSPECT STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,417.738765,9582.066735
107,108,3,GOWANUS,41 TAX CLASS 4 - OTHER,4,471,200,NaN,Z9,459 SMITH STREET,...,NaN,0.000000e+00,NaN,1.0,1.0,1.0,17V1.1,0.0,1700.706977,167505.833958
108,109,3,BUSH TERMINAL,30 WAREHOUSES,4,796,24,NaN,E1,5112 2 AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,1310.490455,90907.250986
109,110,3,SHEEPSHEAD BAY,08 RENTALS - ELEVATOR APARTMENTS,2,8763,7,NaN,D1,1115 BANNER AVENUE,...,NaN,3.087630e+09,11/18/2009,1.0,1.0,1.0,17V1.1,0.0,902.091714,23101.883277
116,117,3,SUNSET PARK,07 RENTALS - WALKUP APARTMENTS,2B,830,33,NaN,C1,364 55TH STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,341.290479,6883.385992
117,118,3,PARK SLOPE,22 STORE BUILDINGS,4,943,240,NaN,K1,120 5TH AVENUE,...,NaN,3.009430e+09,08/18/1997,1.0,NaN,NaN,17V1.1,0.0,1128.324137,70725.668809
131,132,3,WILLIAMSBURG-NORTH,30 WAREHOUSES,4,2357,1,NaN,V1,187 KENT AVENUE,...,E-138,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,594.858063,17365.432923
133,134,3,RED HOOK,30 WAREHOUSES,4,573,100,NaN,E1,68 FERRIS,...,NaN,0.000000e+00,NaN,1.0,1.0,1.0,17V1.1,0.0,2477.922378,204140.844627
153,154,3,SHEEPSHEAD BAY,08 RENTALS - ELEVATOR APARTMENTS,2,7397,34,NaN,D1,1245 AVENUE X,...,NaN,0.000000e+00,NaN,1.0,NaN,1.0,17V1.1,0.0,904.047173,34897.351284
156,157,3,SUNSET PARK,07 RENTALS - WALKUP APARTMENTS,2,723,67,NaN,C1,323 43RD STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,330.224499,6476.037690
159,160,3,BOERUM HILL,31 COMMERCIAL VACANT LAND,4,186,42,NaN,V1,561 PACIFIC STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,450.414432,12200.390212
162,163,3,WILLIAMSBURG-NORTH,30 WAREHOUSES,4,2288,13,NaN,E1,92 NORTH 12,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,634.454418,21679.152878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259197,259198,3,WYCKOFF HEIGHTS,03 THREE FAMILY HOMES,1,3310,1,NaN,C0,279 IRVING AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,227.791741,2021.005127
259198,259199,3,WYCKOFF HEIGHTS,03 THREE FAMILY HOMES,1,3312,43,NaN,C0,411 MENAHAN STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,244.837152,1992.937005
259199,259200,3,WYCKOFF HEIGHTS,03 THREE FAMILY HOMES,1,3338,19,NaN,C0,406 LINDEN STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,252.343095,2164.012460
259200,259201,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3201,16,NaN,C2,332 STARR STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,271.528049,3247.684872
259201,259202,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3201,16,NaN,C2,332 STARR STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,271.528049,3247.684872
259202,259203,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3239,6,NaN,C2,109 ST NICHOLAS AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,232.484100,2310.619578
259203,259204,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3282,17,NaN,C2,426 HIMROD STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,256.780675,2638.335453
259204,259205,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3282,45,NaN,C2,463 HARMAN STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,275.049350,3546.574807
259205,259206,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3290,30,NaN,C2,166 WYCKOFF AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,248.189213,2716.208531
259206,259207,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3302,22,NaN,C3,1516 GREENE AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,274.047016,3421.334253
259207,259208,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3312,22,NaN,C2,430 BLEECKER STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,257.345979,2589.371168
259208,259209,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2B,3386,41,NaN,C1,1503 JEFFERSON AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,578.226045,7449.217079
259209,259210,3,WYCKOFF HEIGHTS,13 CONDOS - ELEVATOR APARTMENTS,2,3238,1019,NaN,R4,101 WYCKOFF AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259210,259211,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3238,33,NaN,S4,118 ST NICHOLAS AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,236.494542,2482.773104
259211,259212,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3239,1,NaN,S3,119 ST NICHOLAS AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,225.144067,1983.384055
259212,259213,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3248,1,NaN,S5,169 IRVING AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,257.962579,2699.216505
259213,259214,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3301,1,NaN,S4,253 IRVING AVE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,420.091721,4040.576412
259214,259215,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3301,38,NaN,S4,198 WYCKOFF AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,251.384160,2509.502193
259215,259216,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3311,3,NaN,S9,257 WYCKOFF AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,252.094649,2606.751812
259216,259217,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3320,35,NaN,S3,429 GROVE STREET,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,224.685160,1980.398753
259217,259218,3,WYCKOFF HEIGHTS,15 CONDOS - 2-10 UNIT RESIDENTIAL,2C,3222,1003,NaN,R1,93 WYCKOFF AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259218,259219,3,WYCKOFF HEIGHTS,22 STORE BUILDINGS,4,3328,1,NaN,K1,1541 MYRTLE AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,343.834251,6051.916290
259219,259220,3,WYCKOFF HEIGHTS,27 FACTORIES,4,3200,1,NaN,F9,49 WYCKOFF AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,594.283822,19138.607249
259220,259221,3,WYCKOFF HEIGHTS,27 FACTORIES,4,3248,12,NaN,F4,1562 DEKALB AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,404.791877,10239.947461
259221,259222,3,WYCKOFF HEIGHTS,27 FACTORIES,4,3248,12,NaN,F4,1562 DEKALB AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,404.791877,10239.947461
259222,259223,3,WYCKOFF HEIGHTS,27 FACTORIES,4,3248,12,NaN,F4,1562 DEKALB AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,404.791877,10239.947461
259223,259224,3,WYCKOFF HEIGHTS,31 COMMERCIAL VACANT LAND,4,3189,137,NaN,V1,267 STARR STREET,...,NaN,3.031890e+09,12/21/2015,1.0,NaN,NaN,17V1.1,0.0,253.385470,2586.519444
259224,259225,3,WYCKOFF HEIGHTS,41 TAX CLASS 4 - OTHER,4,3189,2,NaN,Z9,33 WYCKOFF AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,247.858292,2473.123349
259225,259226,3,WYCKOFF HEIGHTS,41 TAX CLASS 4 - OTHER,4,3189,3,NaN,Z9,33A WYCKOFF AVENUE,...,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,246.475079,2455.818817
259226,259227,3,WYCKOFF HEIGHTS,44 CONDO PARKING,4,3328,1090,NaN,RP,358 GROVE STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:

data = data.drop(columns=[
    'easement',
    'apartment_number',
    'HistDist',
    'Landmark',
    'ZoneMap',
    'EDesigNum',
    'APPDate',
    'FIRM07_FLA',
    'PFIRM15_FL',
    'ZoneDist2',
    'ZoneDist3',
    'ZoneDist3',
    'ZoneDist4',
    'OwnerType',
    'Ext',
    'Overlay1',
    'Overlay2',
    'SPDist1',
    'SPDist2',
    'SPDist3',
    'LtdHeight',
    'ZMCode'])

In [95]:
# NA check, remove columns contianing NA >20000
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print (data.isnull().sum())

Unnamed: 0                    0
borough                       0
neighborhood                  0
building_class_category       0
tax_class                    13
block                         0
lot                           0
building_class               13
address                       0
zip_code                      0
residential_units             0
commercial_units              0
total_units                   0
land_sqft                     0
gross_sqft                    0
year_built                    0
tax_class_at_sale             0
building_class_at_sale        0
sale_price                    0
sale_date                     0
year_of_sale                  0
Borough                    5997
CD                         5997
CT2010                     6031
CB2010                     6099
SchoolDist                 6010
Council                    5997
ZipCode                    5997
FireComp                   6015
PolicePrct                 5997
HealthCent                 5997
HealthArea                 5997
SanitBoro                  6044
SanitDistr                 6044
SanitSub                   6057
Address                    6010
ZoneDist1                  6003
SplitZone                  6010
BldgClass                  6010
LandUse                    6110
Easements                  5997
OwnerName                  6069
LotArea                    5997
BldgArea                   5997
ComArea                    5997
ResArea                    5997
OfficeArea                 5997
RetailArea                 5997
GarageArea                 5997
StrgeArea                  5997
FactryArea                 5997
OtherArea                  5997
AreaSource                 5997
NumBldgs                   5997
NumFloors                  5997
UnitsRes                   5997
UnitsTotal                 5997
LotFront                   5997
LotDepth                   5997
BldgFront                  5997
BldgDepth                  5997
ProxCode                   6010
IrrLotCode                 6010
LotType                    6010
BsmtCode                   6010
AssessLand                 5997
AssessTot                  5997
ExemptLand                 5997
ExemptTot                  5997
YearBuilt                  5997
YearAlter1                 5997
YearAlter2                 5997
BuiltFAR                   5997
ResidFAR                   5997
CommFAR                    5997
FacilFAR                   5997
BoroCode                   5997
BBL                        5997
CondoNo                    5997
Tract2010                  5997
XCoord                     5997
YCoord                     5997
Sanborn                    5997
TaxMap                     5997
APPBBL                     5997
PLUTOMapID                 5997
Version                    5997
MAPPLUTO_F                 5997
SHAPE_Leng                 5997
SHAPE_Area                 5997
dtype: int64

In [96]:
# remove rows having NA
data = data.dropna(axis = 0)
#with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    #print (data.head(3))
data.isnull().sum()
data

,Unnamed: 0,borough,neighborhood,building_class_category,tax_class,block,lot,building_class,address,zip_code,...,XCoord,YCoord,Sanborn,TaxMap,APPBBL,PLUTOMapID,Version,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
4,5,3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,H8,21 CLARK STREET,11201,...,985622.0,193713.0,302 014,30106.0,0.000000e+00,1.0,17V1.1,0.0,620.761169,21360.147631
6,7,3,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,250,44,O4,16 COURT STREET,11241,...,986784.0,191977.0,302 018,30107.0,0.000000e+00,1.0,17V1.1,0.0,460.031680,12947.145471
13,14,3,DOWNTOWN-METROTECH,21 OFFICE BUILDINGS,4,63,1,O6,55 PROSPECT STREET,11201,...,987524.0,194630.0,302 015,30102.0,0.000000e+00,1.0,17V1.1,0.0,621.710684,21360.030189
15,16,3,DOWNTOWN-METROTECH,26 OTHER HOTELS,4,87,9,H8,90 SANDS STREET,11201,...,987811.0,194154.0,302 030,30102.0,0.000000e+00,1.0,17V1.1,0.0,631.446196,21861.418457
19,20,3,DOWNTOWN-METROTECH,21 OFFICE BUILDINGS,4,77,1,O6,77 SANDS STREET,11201,...,987744.0,194462.0,302 016,30102.0,0.000000e+00,1.0,17V1.1,0.0,530.358673,16225.644674
26,27,3,DOWNTOWN-METROTECH,21 OFFICE BUILDINGS,4,87,5,O6,175 PEARL STREET,11201,...,987708.0,194159.0,302 030,30102.0,0.000000e+00,1.0,17V1.1,0.0,635.147432,22260.162205
28,29,3,DOWNTOWN-METROTECH,21 OFFICE BUILDINGS,4,76,1,O6,117 ADAMS STREET,11201,...,987516.0,194475.0,302 015,30102.0,0.000000e+00,1.0,17V1.1,0.0,633.876660,22634.613751
35,36,3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,224,5,H8,107 COLUMBIA HEIGHTS,11201,...,985537.0,194068.0,302 014,30106.0,0.000000e+00,1.0,17V1.1,0.0,616.056218,21001.984085
56,57,3,FORT GREENE,22 STORE BUILDINGS,4,2094,35,K4,633-635 FULTON ST,11201,...,989902.0,190167.0,302 026,30706.0,0.000000e+00,1.0,17V1.1,0.0,485.003860,13224.881521
69,70,3,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,51,25,G1,74 ADAMS STREET,11201,...,987328.0,195026.0,302 015,30101.0,3.000510e+09,1.0,17V1.1,0.0,779.571398,24963.517624
77,78,3,BROOKLYN HEIGHTS,08 RENTALS - ELEVATOR APARTMENTS,2,219,1,D9,97 COLUMBIA HEIGHTS,11201,...,985535.0,194214.0,302 014,30106.0,0.000000e+00,1.0,17V1.1,0.0,562.935418,7726.428939
81,82,3,WILLIAMSBURG-SOUTH,08 RENTALS - ELEVATOR APARTMENTS,2,2159,1,D9,475 KENT AVENUE,11249,...,993103.0,197001.0,303 005,30801.0,3.021590e+09,1.0,17V1.1,0.0,684.590540,25471.032019
86,87,3,BROWNSVILLE,33 EDUCATIONAL FACILITIES,4,3492,1,W9,1501 PITKIN,11212,...,1007042.0,182994.0,316 044,31201.0,3.034920e+09,1.0,17V1.1,0.0,730.241329,31159.103918
87,88,3,CANARSIE,30 WAREHOUSES,4,3650,28,E7,1098 ROCKAWAY AVENUE,11236,...,1010088.0,177005.0,317 024,31204.0,3.036500e+09,1.0,17V1.1,0.0,1253.699337,82862.661173
89,90,3,DOWNTOWN-FULTON MALL,29 COMMERCIAL GARAGES,4,157,1,G1,15 HOYT STREET,11201,...,988420.0,190585.0,302 024,30104.0,3.001570e+09,1.0,17V1.1,0.0,1010.969784,62530.873544
94,95,3,BROOKLYN HEIGHTS,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,239,16,V1,280 CADMAN PLAZA WEST,11201,...,986625.0,192730.0,302 019,30106.0,0.000000e+00,1.0,17V1.1,0.0,702.111881,26116.439809
97,98,3,BUSHWICK,08 RENTALS - ELEVATOR APARTMENTS,2,3170,26,D1,626 BUSHWICK AVENUE,11206,...,1002576.0,193559.0,309 001,31102.0,3.031700e+09,1.0,17V1.1,0.0,810.649949,28578.268442
100,101,3,DOWNTOWN-METROTECH,21 OFFICE BUILDINGS,4,64,25,O6,81 PROSPECT STREET,11201,...,987710.0,194624.0,302 016,30102.0,0.000000e+00,1.0,17V1.1,0.0,417.738765,9582.066735
108,109,3,BUSH TERMINAL,30 WAREHOUSES,4,796,24,E1,5112 2 AVENUE,11232,...,979107.0,175614.0,306A004,30306.0,0.000000e+00,1.0,17V1.1,0.0,1310.490455,90907.250986
109,110,3,SHEEPSHEAD BAY,08 RENTALS - ELEVATOR APARTMENTS,2,8763,7,D1,1115 BANNER AVENUE,11235,...,995827.0,152007.0,318 015,32603.0,3.087630e+09,1.0,17V1.1,0.0,902.091714,23101.883277
116,117,3,SUNSET PARK,07 RENTALS - WALKUP APARTMENTS,2B,830,33,C1,364 55TH STREET,11220,...,979765.0,173830.0,306A018,30307.0,0.000000e+00,1.0,17V1.1,0.0,341.290479,6883.385992
117,118,3,PARK SLOPE,22 STORE BUILDINGS,4,943,240,K1,120 5TH AVENUE,11217,...,990052.0,186740.0,306 028,30401.0,3.009430e+09,1.0,17V1.1,0.0,1128.324137,70725.668809
131,132,3,WILLIAMSBURG-NORTH,30 WAREHOUSES,4,2357,1,V1,187 KENT AVENUE,11249,...,994175.0,200754.0,304 011,30804.0,0.000000e+00,1.0,17V1.1,0.0,594.858063,17365.432923
133,134,3,RED HOOK,30 WAREHOUSES,4,573,100,E1,68 FERRIS,11231,...,979339.0,186987.0,301 002,30207.0,0.000000e+00,1.0,17V1.1,0.0,2477.922378,204140.844627
153,154,3,SHEEPSHEAD BAY,08 RENTALS - ELEVATOR APARTMENTS,2,7397,34,D1,1245 AVENUE X,11235,...,996036.0,155057.0,314 034,32204.0,0.000000e+00,1.0,17V1.1,0.0,904.047173,34897.351284
156,157,3,SUNSET PARK,07 RENTALS - WALKUP APARTMENTS,2,723,67,C1,323 43RD STREET,11232,...,981519.0,176628.0,306A021,30303.0,0.000000e+00,1.0,17V1.1,0.0,330.224499,6476.037690
159,160,3,BOERUM HILL,31 COMMERCIAL VACANT LAND,4,186,42,V1,561 PACIFIC STREET,11217,...,990067.0,188511.0,306 029,30105.0,0.000000e+00,1.0,17V1.1,0.0,450.414432,12200.390212
162,163,3,WILLIAMSBURG-NORTH,30 WAREHOUSES,4,2288,13,E1,92 NORTH 12,11249,...,995820.0,202435.0,304 014,30804.0,0.000000e+00,1.0,17V1.1,0.0,634.454418,21679.152878
164,165,3,CLINTON HILL,08 RENTALS - ELEVATOR APARTMENTS,2,1893,4,D1,97 GRAND STREET,11249,...,994249.0,192259.0,302 054,30701.0,3.018930e+09,1.0,17V1.1,0.0,708.899894,15447.625823
178,179,3,CROWN HEIGHTS,27 FACTORIES,4,1192,63,F5,962 FRANKLIN AVENUE,11225,...,995223.0,181721.0,307 051,30408.0,0.000000e+00,1.0,17V1.1,0.0,605.665258,13310.623088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259192,259193,3,WYCKOFF HEIGHTS,03 THREE FAMILY HOMES,1,3272,37,C0,419 HIMROD STREET,11237,...,1007732.0,196144.0,309 056,31104.0,0.000000e+00,1.0,17V1.1,0.0,243.324861,1939.493502
259193,259194,3,WYCKOFF HEIGHTS,03 THREE FAMILY HOMES,1,3272,37,C0,419 HIMROD STREET,11237,...,1007732.0,196144.0,309 056,31104.0,0.000000e+00,1.0,17V1.1,0.0,243.324861,1939.493502
259194,259195,3,WYCKOFF HEIGHTS,03 THREE FAMILY HOMES,1,3281,19,C0,384 HIMROD STREET,11237,...,1007495.0,195581.0,309 050,31104.0,0.000000e+00,1.0,17V1.1,0.0,243.632795,1992.807508
259195,259196,3,WYCKOFF HEIGHTS,03 THREE FAMILY HOMES,1,3281,19,C0,384 HIMROD STREET,11237,...,1007495.0,195581.0,309 050,31104.0,0.000000e+00,1.0,17V1.1,0.0,243.632795,1992.807508
259196,259197,3,WYCKOFF HEIGHTS,03 THREE FAMILY HOMES,1,3303,15,C0,1554 GREENE AVENUE,11237,...,1008192.0,195631.0,309 056,31105.0,0.000000e+00,1.0,17V1.1,0.0,246.823299,1993.103555
259197,259198,3,WYCKOFF HEIGHTS,03 THREE FAMILY HOMES,1,3310,1,C0,279 IRVING AVENUE,11237,...,1007678.0,194290.0,309 051,31105.0,0.000000e+00,1.0,17V1.1,0.0,227.791741,2021.005127
259198,259199,3,WYCKOFF HEIGHTS,03 THREE FAMILY HOMES,1,3312,43,C0,411 MENAHAN STREET,11237,...,1008467.0,195393.0,309 056,31105.0,0.000000e+00,1.0,17V1.1,0.0,244.837152,1992.937005
259199,259200,3,WYCKOFF HEIGHTS,03 THREE FAMILY HOMES,1,3338,19,C0,406 LINDEN STREET,11237,...,1008758.0,194664.0,309 052,31106.0,0.000000e+00,1.0,17V1.1,0.0,252.343095,2164.012460
259200,259201,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3201,16,C2,332 STARR STREET,11237,...,1006360.0,197090.0,309 055,31102.0,0.000000e+00,1.0,17V1.1,0.0,271.528049,3247.684872
259201,259202,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3201,16,C2,332 STARR STREET,11237,...,1006360.0,197090.0,309 055,31102.0,0.000000e+00,1.0,17V1.1,0.0,271.528049,3247.684872
259202,259203,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3239,6,C2,109 ST NICHOLAS AVENUE,11237,...,1006896.0,196444.0,309 055,31103.0,0.000000e+00,1.0,17V1.1,0.0,232.484100,2310.619578
259203,259204,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3282,17,C2,426 HIMROD STREET,11237,...,1007790.0,195962.0,309 056,31104.0,0.000000e+00,1.0,17V1.1,0.0,256.780675,2638.335453
259204,259205,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3282,45,C2,463 HARMAN STREET,11237,...,1007807.0,195816.0,309 056,31104.0,0.000000e+00,1.0,17V1.1,0.0,275.049350,3546.574807
259205,259206,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3290,30,C2,166 WYCKOFF AVENUE,11237,...,1007476.0,195103.0,309 051,31104.0,0.000000e+00,1.0,17V1.1,0.0,248.189213,2716.208531
259206,259207,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3302,22,C3,1516 GREENE AVENUE,11237,...,1007950.0,195320.0,309 051,31105.0,0.000000e+00,1.0,17V1.1,0.0,274.047016,3421.334253
259207,259208,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2A,3312,22,C2,430 BLEECKER STREET,11237,...,1008438.0,195524.0,309 056,31105.0,0.000000e+00,1.0,17V1.1,0.0,257.345979,2589.371168
259208,259209,3,WYCKOFF HEIGHTS,07 RENTALS - WALKUP APARTMENTS,2B,3386,41,C1,1503 JEFFERSON AVENUE,11237,...,1009725.0,193271.0,309 054,31107.0,0.000000e+00,1.0,17V1.1,0.0,578.226045,7449.217079
259210,259211,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3238,33,S4,118 ST NICHOLAS AVENUE,11237,...,1006879.0,196256.0,309 049,31103.0,0.000000e+00,1.0,17V1.1,0.0,236.494542,2482.773104
259211,259212,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3239,1,S3,119 ST NICHOLAS AVENUE,11237,...,1006977.0,196380.0,309 055,31103.0,0.000000e+00,1.0,17V1.1,0.0,225.144067,1983.384055
259212,259213,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3248,1,S5,169 IRVING AVENUE,11237,...,1006429.0,195228.0,309 049,31103.0,0.000000e+00,1.0,17V1.1,0.0,257.962579,2699.216505
259213,259214,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3301,1,S4,253 IRVING AVE,11237,...,1007469.0,194451.0,309 051,31105.0,0.000000e+00,1.0,17V1.1,0.0,420.091721,4040.576412
259214,259215,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3301,38,S4,198 WYCKOFF AVENUE,11237,...,1007760.0,194874.0,309 051,31105.0,0.000000e+00,1.0,17V1.1,0.0,251.384160,2509.502193
259215,259216,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3311,3,S9,257 WYCKOFF AVENUE,11237,...,1008048.0,194875.0,309 051,31105.0,0.000000e+00,1.0,17V1.1,0.0,252.094649,2606.751812
259216,259217,3,WYCKOFF HEIGHTS,14 RENTALS - 4-10 UNIT,2A,3320,35,S3,429 GROVE STREET,11237,...,1008526.0,194981.0,309 052,31105.0,0.000000e+00,1.0,17V1.1,0.0,224.685160,1980.398753
259218,259219,3,WYCKOFF HEIGHTS,22 STORE BUILDINGS,4,3328,1,K1,1541 MYRTLE AVENUE,11237,...,1008157.0,194129.0,309 052,31105.0,0.000000e+00,1.0,17V1.1,0.0,343.834251,6051.916290
259219,259220,3,WYCKOFF HEIGHTS,27 FACTORIES,4,3200,1,F9,49 WYCKOFF AVENUE,11237,...,1005987.0,196524.0,309 048,31102.0,0.000000e+00,1.0,17V1.1,0.0,594.283822,19138.607249
259220,259221,3,WYCKOFF HEIGHTS,27 FACTORIES,4,3248,12,F4,1562 DEKALB AVENUE,11237,...,1006406.0,195435.0,309 049,31103.0,0.000000e+00,1.0,17V1.1,0.0,404.791877,10239.947461
259221,259222,3,WYCKOFF HEIGHTS,27 FACTORIES,4,3248,12,F4,1562 DEKALB AVENUE,11237,...,1006406.0,195435.0,309 049,31103.0,0.000000e+00,1.0,17V1.1,0.0,404.791877,10239.947461
259222,259223,3,WYCKOFF HEIGHTS,27 FACTORIES,4,3248,12,F4,1562 DEKALB AVENUE,11237,...,1006406.0,195435.0,309 049,31103.0,0.000000e+00,1.0,17V1.1,0.0,404.791877,10239.947461
259223,259224,3,WYCKOFF HEIGHTS,31 COMMERCIAL VACANT LAND,4,3189,137,V1,267 STARR STREET,11237,...,1005864.0,196708.0,300 000,31102.0,3.031890e+09,1.0,17V1.1,0.0,253.385470,2586.519444

In [97]:
# drop attributes
data = data.drop(columns=['neighborhood',
                          'address',
                          'sale_date',
                          'Borough',
                          'ZipCode',
                          'Address',
                          'building_class_category',
                          'XCoord',
                          'YCoord',
                          'Sanborn',
                          'APPBBL',
                          'Version',
                          'PLUTOMapID',
                          'TaxMap',
                          'MAPPLUTO_F',
                          'ZoneDist1',
                          'borough',
                          'year_of_sale',
                          'BoroCode',
                          'CondoNo',
                          'Unnamed: 0',
                          'building_class',
                          'building_class_at_sale',
                          'FireComp',
                          'SanitSub',
                          'BldgClass',
                          'OwnerName'], axis = 1)

In [98]:
y = data.loc[:, 'sale_price']
data = data.drop(['sale_price'],axis = 1)

In [99]:
## one-hot encoding
data = pd.get_dummies(data, dummy_na = True)
# data = pd.concat([data, y], axis = 1)

In [101]:
## split traing, validation and test dataset
X_train, X_test, y_train, y_test = train_test_split(
    data, y, test_size=0.3, random_state=42)
X_train

,block,lot,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,...,tax_class_2B,tax_class_2C,tax_class_4,tax_class_nan,SplitZone_N,SplitZone_Y,SplitZone_nan,IrrLotCode_N,IrrLotCode_Y,IrrLotCode_nan
253569,7911,33,11236,1,0,1,2700.0,1767.0,1945,1,...,0,0,0,0,1,0,0,1,0,0
130930,7012,1,11224,1,0,1,2675.0,1344.0,1989,1,...,0,0,0,0,1,0,0,1,0,0
22280,642,61,11232,2,0,2,1669.0,1920.0,1910,1,...,0,0,0,0,1,0,0,1,0,0
254673,5954,46,11228,1,0,1,2000.0,1536.0,1925,1,...,0,0,0,0,1,0,0,1,0,0
257303,6507,31,11230,2,0,2,4000.0,2472.0,1920,1,...,0,0,0,0,1,0,0,1,0,0
93415,7883,27,11234,1,0,1,2000.0,1288.0,1920,1,...,0,0,0,0,1,0,0,1,0,0
148900,8669,68,11235,0,0,0,0.0,0.0,1931,2,...,0,0,0,0,1,0,0,1,0,0
19614,1785,18,11216,2,0,2,1875.0,2139.0,1899,1,...,0,0,0,0,1,0,0,1,0,0
255285,4999,10,11210,1,0,1,1800.0,1400.0,1925,1,...,0,0,0,0,1,0,0,1,0,0
255276,4976,67,11203,1,0,1,2000.0,1392.0,1925,1,...,0,0,0,0,1,0,0,1,0,0
12841,6596,19,11204,4,0,4,2650.0,3600.0,1927,2,...,0,0,0,0,1,0,0,1,0,0
113389,4452,308,11239,1,0,1,1900.0,1606.0,2016,1,...,0,0,0,0,1,0,0,1,0,0
32018,6366,13,11214,3,0,3,1933.0,2880.0,1920,1,...,0,0,0,0,1,0,0,1,0,0
19881,1942,52,11205,4,1,5,1600.0,2100.0,1949,2,...,0,0,0,0,1,0,0,1,0,0
60486,7628,55,11210,1,0,1,2000.0,1378.0,1920,1,...,0,0,0,0,1,0,0,1,0,0
254989,4021,30,11208,0,0,0,2000.0,0.0,0,1,...,0,0,0,0,1,0,0,1,0,0
6002,3381,53,11221,4,0,4,2000.0,4378.0,1905,2,...,0,0,0,0,1,0,0,1,0,0
94809,2213,57,11211,2,0,2,2000.0,2400.0,1901,1,...,0,0,0,0,1,0,0,1,0,0
124690,6706,14,11230,0,0,0,0.0,0.0,1928,2,...,0,0,0,0,1,0,0,1,0,0
255562,5024,53,11225,88,5,93,10459.0,181360.0,2015,2,...,0,0,0,0,1,0,0,0,1,0
255367,4886,16,11203,2,0,2,4100.0,2048.0,1920,1,...,0,0,0,0,1,0,0,1,0,0
41345,7120,23,11223,1,0,1,1550.0,954.0,1925,1,...,0,0,0,0,1,0,0,1,0,0
24651,5680,32,11219,1,0,1,1803.0,1324.0,1915,1,...,0,0,0,0,1,0,0,1,0,0
88885,5230,14,11210,2,0,2,1800.0,1836.0,1910,1,...,0,0,0,0,1,0,0,1,0,0
79957,8208,14,11236,2,0,2,2000.0,1560.0,1955,1,...,0,0,0,0,1,0,0,1,0,0
253701,8126,9,11236,2,0,2,2500.0,1332.0,1930,1,...,0,0,0,0,1,0,0,1,0,0
114609,8076,67,11236,2,0,2,2000.0,1540.0,1955,1,...,0,0,0,0,1,0,0,1,0,0
28389,1770,83,11206,2,0,2,1875.0,2139.0,1899,1,...,0,0,0,0,1,0,0,1,0,0
13598,6184,62,11204,2,0,2,4000.0,2200.0,1930,1,...,0,0,0,0,1,0,0,1,0,0
87672,4964,11,11226,2,0,2,1958.0,1996.0,1910,1,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121048,1567,18,11233,1,0,1,1462.0,2150.0,1901,1,...,0,0,0,0,1,0,0,1,0,0
32077,7422,112,11235,2,0,2,2625.0,2160.0,1930,1,...,0,0,0,0,1,0,0,1,0,0
28826,5536,54,11204,2,0,2,2300.0,1760.0,1925,1,...,0,0,0,0,1,0,0,1,0,0
251197,6444,1,11214,3,0,3,3007.0,3430.0,1975,1,...,0,0,0,0,1,0,0,0,1,0
9856,5126,6,11226,0,1,1,2050.0,5800.0,1910,4,...,0,0,1,0,1,0,0,1,0,0
14462,6204,46,11204,2,1,3,1439.0,3534.0,1931,1,...,0,0,0,0,1,0,0,1,0,0
23285,685,55,11232,3,0,3,2500.0,1600.0,1910,1,...,0,0,0,0,1,0,0,1,0,0
1841,5719,24,11219,0,0,0,8000.0,0.0,0,4,...,0,0,1,0,1,0,0,1,0,0
21117,1487,66,11233,3,0,3,1900.0,2280.0,1899,1,...,0,0,0,0,1,0,0,1,0,0
117634,5668,65,11219,3,0,3,2437.0,3798.0,1910,1,...,0,0,0,0,1,0,0,1,0,0
67931,3557,3,11212,6,0,6,2500.0,4875.0,1930,2,...,0,0,0,0,1,0,0,1,0,0
258936,2358,24,11249,3,0,3,1940.0,2080.0,1901,1,...,0,0,0,0,1,0,0,1,0,0
67955,1944,4,11238,0,0,0,0.0,0.0,1946,2,...,0,0,0,0,1,0,0,0,1,0
46838,5955,17,11228,1,0,1,1783.0,1170.0,1930,1,...,0,0,0,0,1,0,0,1,0,0
50186,6996,71,11224,5,0,5,4750.0,7540.0,1920,2,...,0,0,0,0,1,0,0,1,0,0
18801,1610,71,11221,2,0,2,1750.0,2364.0,1899,1,...,0,0,0,0,1,0,0,1,0,0
6268,217,1,11201,0,0,0,0.0,0.0,1967,2,...,0,0,0,0,1,0,0,0,1,0
12969,6325,30,11214,3,0,3,8231.0,1476.0,1910,1,...,0,0,0,0,1,0,0,0,1,0
110658,5677,31,11219,1,0,1,3339.0,1621.0,1920,1,...,0,0,0,0,1,0,0,1,0,0
256910,7647,44,11210,1,0,1,3150.0,1983.0,1925,1,...,0,0,0,0,1,0,0,1,0,0
251165,6461,224,11214,2,0,2,1746.0,1890.0,1940,1,...,0,0,0,0,1,0,0,1,0,0
254950,3841,11,11207,3,0,3,2500.0,3198.0,1930,1,...,0,0,0,0,1,0,0,1,0,0
38774,5912,43,11228,3,2,5,3314.0,5025.0,1931,4,...,0,0,1,0,1,0,0,0,1,0
257828,1043,22,11215,8,0,8,2500.0,6856.0,1931,2,...,1,0,0,0,1,0,0,1,0,0
64768,7429,53,11235,2,0,2,2000.0,1760.0,1955,1,...,0,0,0,0,1,0,0,1,0,0
182147,3312,32,11237,3,0,3,1950.0,3357.0,1899,1,...,0,0,0,0,1,0,0,1,0,0
251814,1629,34,11221,4,0,4,1925.0,4200.0,2013,2,...,0,0,0,0,1,0,0,1,0,0
51380,271,47,11201,0,0,0,0.0,0.0,1928,2,...,0,0,0,0,1,0,0,0,1,0
7012,329,26,11231,0,0,0,1750.0,0.0,0,4,...,0,0,1,0,1,0,0,1,0,0
256607,7297,69,11229,0,0,0,3000.0,0.0,0,1,...,0,0,0,0,1,0,0,1,0,0

In [102]:
## scale the train Xs
scaler = preprocessing.StandardScaler().fit(X_train)

X_train_scaled = scaler.transform(X_train) 
X_test_scaled = scaler.transform(X_test) 

## convert to data frame
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns) 
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

y_train = pd.DataFrame(y_train, columns=["sale_price"])
y_test = pd.DataFrame(y_test, columns=["sale_price"])


## integrate the dataset of train and test.

In [ ]:
dataframe.to_csv("./train_scaled_dataset.csv")

In [370]:
# y = pd.DataFrame(y, columns = ['sale_price'])
  
# numeric = data.dtypes[data.dtypes != 'object'].index
# data[numeric] = data[numeric].apply(lambda x: (x-x.mean())/x.std())

In [361]:
# export dataframe
dataframe.to_csv('/Users/Janet/Desktop/111.csv', index = False)